#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'1.23.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.empty(10)

array([4.74071351e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       6.66752297e-310, 4.76418248e-038, 1.16189386e+165, 4.26592186e-090,
       3.73541605e-033, 6.66757055e-310])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
np.empty(5).size * np.empty(5).itemsize
# np.empty(10).size * np.empty(10).itemsize
# np.empty(10).nbytes

40

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a = np.zeros(10).astype(int)
a[4] = 1
print(a)

[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
b = a[::-1]
print(b)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
# np.nonzero(np.array([1,2,0,0,4,0]))
arr = np.array([1,2,0,0,4,0])
arr[arr != 0]

array([1, 2, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
c = np.zeros((3,3))
for i in range(c.shape[0]):
  c[i,i] = 1
print(c)
# np.eye(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.random.randint(100,size = 27).reshape(3,3,3)
# np.random.rand(3,3,3)

array([[[84, 31, 28],
        [18, 85, 76],
        [55, 99, 96]],

       [[84, 99, 23],
        [59, 96, 39],
        [ 8, 25, 30]],

       [[98, 25, 30],
        [90, 52,  6],
        [32, 66, 44]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr = np.random.randint(100,size=(10,10))
print("Max is:",arr.max())
print("Min is:",arr.min())

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr = np.random.randint(100,size=30)
print(arr.mean())

51.46666666666667


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
np.pad?

In [ ]:
a = np.ones((5,5))
a = np.pad(a,2)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
 a = np.zeros((5,5))
 print(a[1:])
 a = np.fill_diagonal(a[1:],[1,2,3,4])
 print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
None


In [ ]:
b = np.array([1,2,3,4])
print(np.diag(b,-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
a = np.zeros((8,8)).astype(int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
d = np.random.randint(100,size=(6,7,8))
print(d)
print(d[,6,7])

[[[10 22 91 66 67 75 34 68]
  [53 19 95 54 19 54 86 77]
  [59 19 25 93 93 89 51 63]
  [72 30 42 17 27 24 67 31]
  [41 85 66 50 23 53 66 60]
  [17 44  2  6 78 20 16 40]
  [83 70 31 94 66  9 39 63]]

 [[63 40 16 91 16 66 89 89]
  [15 95 91  0 82 22 68 37]
  [30 15 61 18 99 83 56 51]
  [ 8 56 73 73 68 30 55 32]
  [99 85 97 39 63 35 25 76]
  [40 54 40 71 99 11  5 46]
  [41 88 51 71 95 83 24 39]]

 [[49 28 83 59 65 77 85 68]
  [29 62 42 43  2 24 60 79]
  [26 24 58  0 58 62 42 54]
  [11  7 98 91 88  3 36 13]
  [62  4 70 26 78 54 56 42]
  [65  3 44 20 16 45  5 11]
  [87  4 22 94 66 59 14 50]]

 [[70 18 85  9 57 92 64 12]
  [61 51 22 89 85  6 13 26]
  [16 31 40 38 20 70 66 17]
  [75 67 10  7  4 94 25 83]
  [11 71  4 51 41 42 36 57]
  [15 62 15 91 43 55 79 98]
  [ 0 48  0 20 87 16 42 91]]

 [[11 79 65 60 91 68 50 89]
  [68 38  3 54 77 34  5  5]
  [64 53 86 14 32 98 16 77]
  [44 55 71 39 68 28 38 63]
  [43 44 95 43 65 58 34 84]
  [21  3 66 21 37 60 43 79]
  [14 91 64  2  1 96 22 58]]

 [[ 5 62 1

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
a = np.array([[0,1],[1,0]])
r = ((4,4))
print(np.tile(a,r))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
b = np.random.normal(size=(5,5))
print(b)

[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]]
[[-1.64476575  0.64081453  0.61967119  0.63813715  1.88546985]
 [ 0.88578501 -0.34436637 -0.04848473  0.94612956 -1.48662058]
 [ 0.82833085  0.84310567 -0.91352457 -1.22441405 -0.51260228]
 [-0.32832552  0.45975784 -0.04249428  2.05579045 -1.32701109]
 [-0.91927169 -1.10081886  0.77620165 -0.74975607  0.06326207]]


In [ ]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.20057658 -1.55885469 -1.55236385  0.85467592 -0.62141587]
 [-1.45841232  1.28742646 -0.8012318   0.65083622  0.56143758]
 [ 1.12817669  0.19278512  0.65130577 -0.79715177 -1.08166122]
 [ 1.17349953 -0.51184108  1.42192177  0.33606326  0.18566436]
 [-1.64074024  1.36661698 -0.43322604  0.02964403 -0.58373141]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
b = np.array([('r',np.ubyte),('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a = np.random.randint(100,size=(5,3))
b = np.random.randint(100,size=(3,2))
print(np.dot(a,b))

[[ 3192  9061]
 [ 4548 12297]
 [ 5076 10483]
 [ 4332  9192]
 [ 6996 15838]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a = np.random.randint(10,size = 10)
a[(a > 3) & (a < 8)] *= -1
print(a)

[ 2 -5 -5  0  8  1  1  0  3  8]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: ignored

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
import numpy as np
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-13-b45964de3b69>:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0)/np.array(0))
<ipython-input-13-b45964de3b69>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [12]:
import numpy as np
a = np.random.uniform(-5,5,6)
print(np.copysign(np.ceil(np.abs(a)),a))

[ 3.  4. -1. -5.  1. -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a = np.random.randint(10,size=3)
b = np.random.randint(10,size=4)
print(a,"\t",b)
print(np.intersect1d(a,b))

[1 6 2] 	 [7 1 2 9]
[1 2]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
d = np.seterr(all = "ignore")
np.ones(1)/0
_ = np.seterr(**d)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.emath.sqrt(-1))
print(np.sqrt(-1))
print(np.sqrt(-1) == np.emath.sqrt(-1))

1j
nan
False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
print("Yesterday:{}".format(np.datetime64("today") - np.timedelta64(1)))
print("Today:{}".format(np.datetime64("today")))
print("Tomorrow:{}".format(np.datetime64("today") + np.timedelta64(1)))

Yesterday:2023-09-26
Today:2023-09-27
Tomorrow:2023-09-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
a = np.ones(3)
b = np.ones(3)*2
np.add(a,b,out=b)
np.negative(a,out=a)
np.divide(a,2,out=a)
print(np.multiply(a,b))

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
a = np.random.uniform(0,10,10)
print(a // 1)
print(a.astype(int))
print(a - a%1)
print(np.floor(a))

[8. 7. 9. 0. 8. 6. 3. 4. 2. 2.]
[8 7 9 0 8 6 3 4 2 2]
[8. 7. 9. 0. 8. 6. 3. 4. 2. 2.]
[8. 7. 9. 0. 8. 6. 3. 4. 2. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generator():
  for i in range(10):
    yield i
arr = np.fromiter(generator(),dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
np.linspace?

In [ ]:
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
a = np.random.random(10)
a.sort()
print(a)

[0.01433354 0.06576575 0.22801848 0.28523299 0.33539936 0.34300689
 0.76913787 0.81999401 0.85124074 0.966984  ]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
a = np.arange(10)
np.add.reduce(a)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,10,5)
B = np.random.randint(0,10,5)
print(np.array_equal(A,B))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
import numpy as np
a = np.zeros(10)
a.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
a = np.random.random((10,2))
b,c = a[:,0], a[:,1]
d = np.sqrt(b**2+c**2)
e = np.arctan2(c,b)
print(d)
print(e)

[0.05617227 0.09821867 1.01404508 0.93182201 0.39065868 0.62043311
 0.6162781  0.13621694 0.50229488 1.02507517]
[0.37223903 0.19496898 1.15895478 0.51649317 0.15278287 0.26761995
 1.13006283 0.62720401 1.56604805 1.12091957]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
a = np.random.randint(20,size=10)
print(a)
a[a.argmax()] = 0
print(a)

[ 7 18  4 14 17  2 14 11 17 14]
[ 7  0  4 14 17  2 14 11 17 14]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

86


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [17]:
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-17-1c50e4e32ac3>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [16]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.60698844 0.2482339  0.81869276 0.46443813 0.61608724
  0.77268072 0.63682505 0.28477116 0.55836775]
 [0.60698844 0.         0.75349357 0.41325285 0.78723367 0.31323189
  0.45330933 0.50451171 0.66630208 0.04928113]
 [0.2482339  0.75349357 0.         0.84729202 0.25686592 0.65419289
  0.77502476 0.59661477 0.13421932 0.70954634]
 [0.81869276 0.41325285 0.84729202 0.         0.74705849 0.20270259
  0.10402549 0.29611975 0.71946276 0.43573816]
 [0.46443813 0.78723367 0.25686592 0.74705849 0.         0.5865061
  0.65543615 0.45728724 0.18196549 0.75324038]
 [0.61608724 0.31323189 0.65419289 0.20270259 0.5865061  0.
  0.17356237 0.19834803 0.53112976 0.3134817 ]
 [0.77268072 0.45330933 0.77502476 0.10402549 0.65543615 0.17356237
  0.         0.19902017 0.64379088 0.46557171]
 [0.63682505 0.50451171 0.59661477 0.29611975 0.45728724 0.19834803
  0.19902017 0.         0.46273357 0.49679044]
 [0.28477116 0.66630208 0.13421932 0.71946276 0.18196549 0.53112976
  0.64379088 0.462733

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [18]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[82  4 29 24 41 88 44 41 16 99]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [20]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-20-3055aefe133f>:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [21]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [22]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [23]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [24]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.04677052 -0.19347681 -0.35224003  0.28296118  0.39354171 -0.24508985
   0.09206873 -0.01346649 -0.11623239  0.19870449]
 [-0.1054864  -0.11502674  0.37364052 -0.1875384   0.39627998 -0.32968505
   0.07111703 -0.12996869  0.07252671 -0.04585897]
 [ 0.21555616 -0.2897598   0.33863955  0.14788247 -0.54643193  0.19192502
   0.2563044  -0.07141631  0.28418854 -0.5268881 ]
 [ 0.24145639 -0.40322181  0.22684816  0.19972834  0.20426115  0.28149092
  -0.32649136 -0.21005463  0.27436858 -0.48838575]
 [ 0.27606001  0.21824532 -0.33327585 -0.29259102 -0.05268667  0.08842836
   0.03673468 -0.10767528  0.02251383  0.14424663]]


#### 59. How to sort an array by the nth column? (★★☆)

In [25]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[0 3 3]
 [7 8 4]
 [9 9 4]]
[[0 3 3]
 [7 8 4]
 [9 9 4]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [26]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [27]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.48428100374859484


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [28]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [29]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [30]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)



[4. 6. 2. 2. 4. 2. 3. 1. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [31]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [32]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [34]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 17) ( 1, 97) ( 5, 25) ( 5, 57) ( 5, 63) ( 5, 81) (12, 15) (12, 18)
 (15, 18) (17, 97) (20, 21) (21, 21) (25, 63) (30, 66) (30, 81) (31, 45)
 (31, 66) (32, 57) (32, 88) (42, 48) (42, 83) (45, 66) (48, 83) (57, 81)
 (57, 88) (65, 82) (65, 84) (66, 81) (82, 84)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)